### ISSUE TITLE
Formatter parameter in component fields doesn't work when attribute is set

### ISSUE THREAD

**Issue by cshawaus** [aem-design/aemdesign-aem-core#25]
**Current Behavior**
Lets take the below example:

```java
{"cq:tags", new String[]{}, "data-tags", Tag.class.getCanonicalName()}
```

When `data-tags` is set, `Tag.class.getCanonicalName()` no longer gets used which can cause confusion.

**Expected behavior/code**
Passing a 4th formatter parameter should still work when an HTML attribute value is given.

**Comment by wildone** [comment]
I have reviewed this on clean docker image. Ive added some Primary Categories and they appear as follows:

![image](https://user-images.githubusercontent.com/170312/80306383-4eb6b700-8806-11ea-9d75-b52375e48f95.png)

Any more info?

**Comment by cshawaus** [comment]
Looks to be an issue with an older version, happy to close this.
